In [1]:
import numpy as np

In [2]:
b= np.zeros(5)

In [3]:
b

array([0., 0., 0., 0., 0.])

In [4]:
b.dtype

dtype('float64')

In [5]:
a = np.empty(4)

In [6]:
a

array([ 9.76118064e-313,  2.46151512e-312,  2.37663529e-312,
       -3.42196482e-210])

In [9]:
a.shape = (2,2)

In [10]:
a

array([[ 9.76118064e-313,  2.46151512e-312],
       [ 2.37663529e-312, -3.42196482e-210]])

In [11]:
c= np.linspace(1,5,5)

In [12]:
c

array([1., 2., 3., 4., 5.])

In [13]:
d=np.arange(3,20,4)

In [14]:
d

array([ 3,  7, 11, 15, 19])

In [15]:
f=np.array((5, 8, 3))

In [16]:
f

array([5, 8, 3])

In [18]:
l1 = [1, 2, 3, 4, 5],[1, 2, 4, 7, 6]

In [19]:
g= np.array((l1))

In [20]:
g

array([[1, 2, 3, 4, 5],
       [1, 2, 4, 7, 6]])

In [21]:
g.shape

(2, 5)

In [22]:
w= np.random.randint(50, size=6)

In [23]:
w

array([12, 33, 48, 39, 19, 49])

In [25]:
w[3]

39

In [26]:
w[1:4]

array([33, 48, 39])

In [27]:
w[-2]

19

In [28]:
w<20

array([ True, False, False, False,  True, False])

In [30]:
w*2/3

array([ 8.        , 22.        , 32.        , 26.        , 12.66666667,
       32.66666667])

In [32]:
w+40-90

array([-38, -17,  -2, -11, -31,  -1])

In [35]:
array([-3, -5, -14, -6])

In [ ]:
result = np.array([34, 54, 65, 12])

In [38]:
np.where(result>32,"PASS", "FAIL try agian")